In [ ]:
n=int(input("enter A:"))
if(n>0):
  print("positive")
elif(n==0):
    print("Zero")
else:
  print("negative")

enter A:-5
negative


In [ ]:
n=int(input("enter A:"))
if n>0:
  print("positive")
elif(n==0):
  print("zero")
else:
  print("negative")


enter A:10
positive


In [ ]:
x=4
x="sooraj"
print(x)

sooraj


In [ ]:
a,b,c="sajith","sooraj","akash"
print(a)
print(b)
print(c)

sajith
sooraj
akash


In [ ]:
integer=[1,2,3]
a,b,c=integer
print(a)
print(b)
print(c)

1
2
3


In [ ]:
def sooraj(a,b):
  print(a+b)
sooraj(10,15)


25


In [ ]:
a=10
b=13
def myfunc():
  #a=20
  #b=15
  print(a+b)
myfunc()
print(a+b)

23
23


In [ ]:
def myfunc():
  global x
  x = "sooraj"
  print(x)
myfunc()
print(x)

sooraj
sooraj


In [ ]:
x=12
a=float(x)#casting
print(a)

12.0


In [ ]:
x=1.2
a=int(x)
print(a)

1


In [ ]:
z=1
a=complex(z)
print(a)

(1+0j)


In [ ]:
import random#for fetching random range
print(random.randrange(1,100))

59


In [ ]:
a="""my name is sooraj
my native is theni"""
print(a)

my name is sooraj
my native is theni


In [ ]:
a="hello, world!"
print(a[6])

In [ ]:
a="banana"
for i in a:
  print(i)

b
a
n
a
n
a


In [ ]:
a="hello, world!"
print(len(a))

13


In [ ]:
sooraj="my name praveen"
print("praveen" in sooraj)

False


In [ ]:
#slicing
b="hello, world"
print(b[2:7])

llo, 


In [ ]:
b="hello, world"
print(b[:7])

hello, 


In [ ]:
#lower
a="sooraj"
print(a.upper())

SOORAJ


In [ ]:
#lower
a="SOORAJ"
print(a.lower())

sooraj


In [ ]:
#strip
a=" Hello, world!"
print(a.strip())

Hello, world!


In [ ]:
#replace
a="Hello, world"
print(a.replace("Hello","good"))

good, world


In [ ]:
#split
a="hello. world"
print(a.split("."))

['hello', ' world']


In [ ]:
a=["sajith","akash","sooraj"]
print(a)

['sajith', 'akash', 'sooraj']


In [ ]:
list1=["sajith","akash","sooraj"]
list2=["murali","shahi","kanness"]
print(list1+list2)

['sajith', 'akash', 'sooraj', 'murali', 'shahi', 'kanness']


In [ ]:
[2]

In [ ]:
a=["sajith","akash","sooraj"]
a[2]="sanjay"
print(a)

['sajith', 'akash', 'sanjay']


In [ ]:
a.insert(2,"arun")
print(a)

['sajith', 'akash', 'arun', 'sooraj']


In [ ]:
a.remove(a[2])
print(a)

['sajith', 'akash']


In [ ]:
a=[5,2,4,6,1,8]
a.sort()
print(a)

[1, 2, 4, 5, 6, 8]


In [ ]:
a=[5,2,4,6,1,8]
a.sort(reverse=True)
print(a)

[8, 6, 5, 4, 2, 1]


In [ ]:
a=["sajith","akash","sooraj"]
a.sort(reverse=True)
print(a)

['sooraj', 'sajith', 'akash']


In [ ]:
a=["sajith","akash","sooraj"]
list=a.copy()
print(list)

['sajith', 'akash', 'sooraj']


In [ ]:
a=("asd","cxz","wqx")
print(len(a))

3


In [ ]:
x=["sooraj"]
tuple(x)

('sooraj',)

In [ ]:
x=("sooraj")
list(x)

TypeError: ignored

In [ ]:
import numpy as np
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
a=np.array([1,2,3,4])
a[2]

3

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,4,5],[7,8,6]])
c=np.concatenate((a,b),axis=1)
print(c)


[[1 2 3 2 4 5]
 [4 5 6 7 8 6]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,2,1],[6,3,2]])
b[3,1]

3

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,6,4]]])
a[1,1,2]

4

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,2,1],[6,3,2]])
print(b[0:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,6,4]]])
print(a[1,1,0:2])

[5 6]


In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,6,4]]])
for i in a:
  print(i)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [5 6 4]]


In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,2,1],[6,3,2]])
for i in b:
  for c in i:
    print(c)

1
2
3
4
5
6
7
2
1
6
3
2
